#ifndef CONTROLLER_STATIC_TABLES_H
#define CONTROLLER_STATIC_TABLES_H

#include <stdint.h>

typedef struct {
	uint32_t match;
	uint32_t mask;
	uint32_t value;
	uint32_t square;
	uint32_t cube;
} log_square_entry_t;

#include "autogenerated/static_tables.h"

#endif //CONTROLLER_STATIC_TABLES_H
